const assert=require('node:assert/strict');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const ts=require('../mobile/node_modules/typescript');
const file=fs.readFileSync(path.join(__dirname,'../mobile/src/screens/Directory.tsx'),'utf8');
const js=ts.transpileModule(file,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const target={exports:{},require(name){
 if(name==='react')return {default:{}};
 if(name==='react-native')return {};
 if(name==='../theme')return {C:{green:'green',red:'red',orange:'orange',muted:'muted'}};
 if(name.startsWith('../components/')||name.startsWith('./ClientProfile')||name.startsWith('./RecordDetails'))return {};
 throw Error('Unexpected import: '+name);
}};
vm.runInNewContext(js,target);
const {matchesRecordStatus,listRecordSummary}=target.exports;
assert.equal(matchesRecordStatus('services','Cancelled','focus'),false);
assert.equal(matchesRecordStatus('services','Cancelled','all'),true);
assert.equal(matchesRecordStatus('services','Active','focus'),true);
assert.equal(matchesRecordStatus('invoices','Paid','focus'),false);
assert.equal(matchesRecordStatus('invoices','Unpaid','focus'),true);
assert.equal(matchesRecordStatus('invoices','Paid','paid'),true);
assert.equal(matchesRecordStatus('orders','Pending','focus'),true);
assert.equal(matchesRecordStatus('orders','Active','focus'),false);
assert.equal(matchesRecordStatus('orders','Active','all'),true);
const invoice=listRecordSummary('invoices',{id:301,amount:90,currency:'USD',due:'2026-10-11',customer:'John'});
assert.equal(invoice.title,'فاتورة #301');
assert.equal(invoice.primary,'90 USD • الاستحقاق 2026-10-11');
const service=listRecordSummary('services',{id:22,domain:'example.test',plan:'Starter',renewal:'2026-11-01'});
assert.equal(service.title,'example.test');
assert.equal(service.primary,'Starter • التجديد 2026-11-01');
const order=listRecordSummary('orders',{id:7,product:'VPS',created:'2026-10-09'});
assert.equal(order.title,'طلب #7');
assert.equal(order.primary,'VPS • 2026-10-09');
const detail=fs.readFileSync(path.join(__dirname,'../mobile/src/screens/RecordDetails.tsx'),'utf8');
for(const token of ["GetInvoice","GetClientsProducts","GetOrders","UpdateInvoice","UpdateClientProduct","AcceptOrder","CancelOrder","autosetup:0","sendemail:0","detailIdentityMatches","confirm('قبول الطلب'"])assert.ok(detail.includes(token),token);
assert.ok(!detail.includes('Object.entries(read)'),'No raw all-fields dump');
console.log('PASS: compact invoice/service/order lists, status filters, WHMCS detail identity and explicit confirmed management');
