import {readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'..');
const get=p=>readFileSync(resolve(root,p),'utf8');
const code=get('mobile/src/lib/api.ts');
assert.match(code,/includes\/api\.php/);
assert.match(code,/https:/);
assert.match(code,/SecureStore/);
assert.match(code,/GetAdminDetails/);
assert.match(code,/AddTicketReply/);
assert.doesNotMatch(code,/ontrack_mobile_admin\/bridge\.php/);
assert.ok(!existsSync(resolve(root,'whmcs')));
for(const name of ['mobile/App.tsx','mobile/src/screens/Connect.tsx','mobile/src/screens/Explorer.tsx']) assert.doesNotMatch(get(name),/(<WebView|react-native-webview|<iframe)/i);
const actions=get('mobile/src/catalog/actions.ts');
assert.match(actions,/GetClientsProducts/);
assert.match(actions,/GetInvoices/);
assert.match(actions,/GetTickets/);
for(const name of ['mobile/src/screens/WhatsApp.tsx','mobile/src/lib/adminSession.ts']) assert.doesNotMatch(get(name),/(<WebView|react-native-webview|<iframe)/i);
assert.doesNotMatch(get('mobile/src/lib/adminSession.ts'),/Linking\\.openURL/);
assert.ok(get('mobile/src/screens/WhatsApp.tsx').includes('existingWhatsAppInboxUrl'));
assert.ok(get('mobile/src/screens/WhatsApp.tsx').includes('checkedAdminUrl(baseUrl,dir'));
assert.ok(get('mobile/src/screens/WhatsApp.tsx').includes("session.mode==='admin'"));
assert.ok(!get('mobile/src/screens/WhatsApp.tsx').includes('<AdminAccess'));
assert.ok(get('mobile/src/lib/adminSession.ts').includes('adminDirectoryStorageKey'));
assert.ok(get('mobile/src/lib/adminSession.ts').includes('saveAdminDirectory'));
assert.ok(get('mobile/src/screens/WhatsApp.tsx').includes('Linking.openURL(target)'));
assert.ok(get('mobile/src/screens/WhatsApp.tsx').includes('loginAdmin(session,dir,session.username,session.password,otp.trim())'));
assert.ok(!get('mobile/src/screens/WhatsApp.tsx').includes('if(session.mode===\'api\')return <AdminAccess'));
assert.match(get('mobile/src/lib/whatsapp.ts'),/chat_list/);
assert.match(get('mobile/src/lib/whatsapp.ts'),/X-WA-CSRF/);
assert.match(get('mobile/src/lib/whatsapp.ts'),/getWhatsAppRetryAfterMs/);
assert.match(get('mobile/src/screens/WhatsApp.tsx'),/لا تُعد الإرسال/);
assert.match(get('mobile/native/android/CommandAdminSessionModule.java'),/CookiePolicy.ACCEPT_ORIGINAL_SERVER/);
assert.ok(!get('mobile/native/android/CommandAdminSessionModule.java').includes('CookieHandler.setDefault'));
assert.ok(get('mobile/src/screens/ClientProfile.tsx').includes('fetchClientTab'));
assert.ok(get('mobile/src/screens/ClientProfile.tsx').includes('RecordDetails'));
assert.ok(get('mobile/src/screens/Directory.tsx').includes('matchesRecordStatus'));
assert.ok(get('mobile/src/screens/RecordDetails.tsx').includes('UpdateClientProduct'));
assert.ok(get('mobile/src/screens/RecordDetails.tsx').includes('GetInvoice'));
assert.ok(get('mobile/src/lib/clientProfile.ts').includes('GetClientsDetails'));
assert.match(code,/number:s\(x\.tid\|\|x\.id\)/);
assert.match(code,/totalresults/);
assert.match(code,/loadPage/);
assert.match(get('mobile/App.tsx'),/SafeAreaProvider/);
assert.match(get('mobile/App.tsx'),/BackHandler\.exitApp/);
assert.match(get('mobile/src/screens/Connect.tsx'),/__DEV__/);
assert.equal(JSON.parse(get('mobile/app.json')).expo.version,'0.3.12');
assert.equal(JSON.parse(get('mobile/app.json')).expo.android.versionCode,23);
assert.ok(JSON.parse(get('mobile/package.json')).dependencies['react-native-safe-area-context']);
assert.ok(get('mobile/src/lib/adminSession.ts').includes('proveAdminAccess'));
assert.ok(get('mobile/src/lib/adminSession.ts').includes('isVerifiedWhatsAppInbox'));
assert.ok(!get('mobile/src/screens/WhatsApp.tsx').includes('<AdminAccess key={error}'));
assert.ok(get('mobile/src/lib/adminSession.ts').includes('whatsappAccessDiagnostic'));
assert.ok(get('mobile/src/components/AdminAccess.tsx').includes('Administrator'));

console.log('PASS: source integrity plus ticket external ID, pagination, safe areas, Android Back, version increment and demo isolation');

const updateCode=get('mobile/src/components/UpdateGate.tsx');
assert.ok(updateCode.includes('agent.ontrackegy.com/api/app/latest.php'));
assert.ok(updateCode.includes('CommandUpdateInstaller'));
assert.ok(updateCode.includes('appConfig.expo.android.versionCode'));
assert.ok(updateCode.includes('whmcs-check-update'));
assert.ok(get('mobile/src/screens/Settings.tsx').includes('فحص التحديثات'));
assert.ok(code.includes('getApiRetryAfterMs'));
assert.ok(code.includes('REQUEST_SPACING_MS'));
assert.ok(code.includes('loadOverview(session:Session,keys:SectionKey[]'));
assert.ok(get('mobile/App.tsx').includes('minHeight:60'));
assert.ok(get('mobile/src/screens/Directory.tsx').includes('ClientProfile'));
assert.ok(get('mobile/src/lib/api.ts').includes('GetClientsDetails'));
assert.ok(code.includes('response.status===429'));
assert.ok(!updateCode.includes('Linking.openURL'));
const nativeUpdate=get('mobile/native/android/CommandUpdateModule.java');
assert.ok(nativeUpdate.includes('FileProvider.getUriForFile'));
assert.ok(nativeUpdate.includes('APK SHA256 mismatch'));
console.log('PASS: native website APK downloader, checksum verification, Android installer');

assert.equal(JSON.parse(get('mobile/app.json')).expo.name,'WHMCS');
assert.equal(JSON.parse(get('mobile/app.json')).expo.android.package,'com.ontrackdevelopment.command');
assert.ok(get('mobile/src/components/UpdateGate.tsx').includes('WHMCS-v'));
assert.ok(get('mobile/native/android/CommandUpdateModule.java').includes('WHMCS-v'));
console.log('PASS: WHMCS identity and icon config, stable Android package and updates');

const ticketScreen=get('mobile/src/screens/Tickets.tsx');
const ticketClient=get('mobile/src/lib/tickets.ts');
assert.ok(ticketScreen.includes('التذاكر المسندة'));
assert.ok(ticketScreen.includes('fetchTicketQueue'));
assert.ok(ticketScreen.includes('إرفاق توقيع الأدمن'));
assert.ok(ticketClient.includes('My Flagged Tickets'));
assert.ok(ticketClient.includes('Awaiting Reply'));
assert.ok(ticketClient.includes('ticketMatchesQueue'));
assert.ok(ticketClient.includes('parseTicketCustomFields'));
assert.ok(ticketScreen.includes('الحقول المخصصة للتذكرة'));
assert.ok(ticketScreen.includes('إرجاع التذكرة إلى المساعد AI'));
assert.ok(code.includes('buildReplyParams'));
assert.ok(code.includes('params.clientid=owner'));
assert.ok(ticketScreen.includes('showAssigned?section'));
assert.ok(get('mobile/App.tsx').includes('onContentSizeChange'));
assert.ok(ticketClient.includes('GetAdminDetails'));
assert.ok(get('mobile/App.tsx').includes('KeyboardAvoidingView'));
assert.ok(get('mobile/App.tsx').includes('keyboardVisible'));
assert.equal(JSON.parse(get('mobile/app.json')).expo.android.softwareKeyboardLayoutMode,'resize');
console.log('PASS: ticket queue separation, operator signature, keyboard resizing and safe navigation');

assert.ok(get('mobile/src/lib/adminSession.ts').includes('validateAdminDirectory(directory,session.baseUrl'));
assert.ok(get('mobile/src/components/AdminAccess.tsx').includes('اختبار فتح رابط الإدارة بالمتصفح'));
