import {readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'..');
const get=p=>readFileSync(resolve(root,p),'utf8');
const code=get('mobile/src/lib/api.ts');
assert.match(code,/includes\/api\.php/);
assert.match(code,/https:/);
assert.match(code,/SecureStore/);
assert.match(code,/GetAdminDetails/);
assert.match(code,/AddTicketReply/);
assert.doesNotMatch(code,/ontrack_mobile_admin\/bridge\.php/);
assert.ok(!existsSync(resolve(root,'whmcs')));
for(const name of ['mobile/App.tsx','mobile/src/screens/Connect.tsx','mobile/src/screens/Explorer.tsx']) assert.doesNotMatch(get(name),/(<WebView|react-native-webview|<iframe)/i);
const actions=get('mobile/src/catalog/actions.ts');
assert.match(actions,/GetClientsProducts/);
assert.match(actions,/GetInvoices/);
assert.match(actions,/GetTickets/);
assert.match(get('mobile/src/screens/WhatsApp.tsx'),/API موثّق/);
assert.match(code,/number:s\(x\.tid\|\|x\.id\)/);
assert.match(code,/totalresults/);
assert.match(code,/loadPage/);
assert.match(get('mobile/App.tsx'),/SafeAreaProvider/);
assert.match(get('mobile/App.tsx'),/BackHandler\.exitApp/);
assert.match(get('mobile/src/screens/Connect.tsx'),/__DEV__/);
assert.equal(JSON.parse(get('mobile/app.json')).expo.version,'0.2.5');
assert.equal(JSON.parse(get('mobile/app.json')).expo.android.versionCode,6);
assert.ok(JSON.parse(get('mobile/package.json')).dependencies['react-native-safe-area-context']);
console.log('PASS: source integrity plus ticket external ID, pagination, safe areas, Android Back, version increment and demo isolation');

const updateCode=get('mobile/src/components/UpdateGate.tsx');
assert.ok(updateCode.includes('agent.ontrackegy.com/api/app/latest.php'));
assert.ok(updateCode.includes('CommandUpdateInstaller'));
assert.ok(!updateCode.includes('Linking.openURL'));
const nativeUpdate=get('mobile/native/android/CommandUpdateModule.java');
assert.ok(nativeUpdate.includes('FileProvider.getUriForFile'));
assert.ok(nativeUpdate.includes('APK SHA256 mismatch'));
console.log('PASS: native website APK downloader, checksum verification, Android installer');

assert.equal(JSON.parse(get('mobile/app.json')).expo.name,'WHMCS');
assert.equal(JSON.parse(get('mobile/app.json')).expo.android.package,'com.ontrackdevelopment.command');
assert.ok(get('mobile/src/components/UpdateGate.tsx').includes('WHMCS-v'));
assert.ok(get('mobile/native/android/CommandUpdateModule.java').includes('WHMCS-v'));
console.log('PASS: WHMCS identity and icon config, stable Android package and updates');
