import React,{useState} from 'react';
import {Alert,KeyboardAvoidingView,Platform,ScrollView,TextInput,View} from 'react-native';
import {C} from '../theme';
import type {Session} from '../types';
import {Action,Card,Icon,Pill,T} from '../components/UI';
const blank:Session={baseUrl:'https://services.ontrackegy.com',mode:'api',username:'',password:'',accessKey:'',identifier:'',secret:''};
export function Connect({onPair,onDemo}:{onPair:(config:Session)=>Promise<void>,onDemo:()=>void}){
 const [c,setC]=useState(blank),[busy,setBusy]=useState(false);
 const edit=(k:keyof Session)=>(v:string)=>setC(s=>({...s,[k]:v}));
 const input=(label:string,k:keyof Session,secret=false)=> <View style={{gap:6}} key={k}><T weight="700">{label}</T><TextInput value={c[k]} onChangeText={edit(k)} autoCapitalize="none" autoCorrect={false} secureTextEntry={secret} placeholder={label} placeholderTextColor={C.muted} style={{color:C.text,backgroundColor:C.surface2,padding:14,borderRadius:12,textAlign:'left',minHeight:47}}/></View>;
 const required=c.mode==='api'?!!(c.identifier.trim()&&c.secret):!!(c.username.trim()&&c.password);
 return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,backgroundColor:C.bg}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,paddingTop:65,paddingBottom:40}}><View style={{alignItems:'center',marginBottom:25,gap:9}}><View style={{backgroundColor:C.redDark,padding:19,borderRadius:25}}><Icon name="shield-crown" size={42} color={C.red}/></View><T weight="900" size={29}>WHMCS</T><T color={C.muted}>ربط مباشر بواجهة WHMCS الرسمية</T></View><Card style={{gap:13}}><T size={18} weight="800">الاتصال بالسيرفر</T>{input('رابط WHMCS (HTTPS)','baseUrl')}<T weight="700">طريقة المصادقة</T><View style={{flexDirection:'row-reverse',gap:10}}><View style={{flex:1}}><Action label="API Credentials" secondary={c.mode!=='api'} onPress={()=>setC(s=>({...s,mode:'api'}))}/></View><View style={{flex:1}}><Action label="Admin Legacy" secondary={c.mode!=='admin'} onPress={()=>setC(s=>({...s,mode:'admin'}))}/></View></View>{c.mode==='api'?<>{input('API Identifier','identifier')}{input('API Secret','secret',true)}<T color={C.orange} size={11}>أنشئ API Credentials بصلاحيات محدودة من WHMCS. المفاتيح محفوظة على هذا الجهاز مشفّرة؛ الأفضل عدم استخدام بيانات Super Admin.</T></>:<>{input('Admin Username','username')}{input('Admin Password','password',true)}{input('API Access Key','accessKey',true)}<T color={C.orange} size={11}>وضع توافق مع التطبيق الرسمي القديم. بيتطلب صلاحية API Access وقد تتأثر الاتصالات بقيود IP.</T></>}<Action label={busy?'جارٍ الاتصال...':'اختبار الاتصال وحفظه'} disabled={busy||!required} icon="link-variant" onPress={async()=>{setBusy(true);try{await onPair(c);}catch(e){Alert.alert('الاتصال',e instanceof Error?e.message:'تعذر الاتصال');}finally{setBusy(false);}}}/></Card>{__DEV__?<View style={{marginTop:16,gap:12}}><Action label="تجربة الواجهات (للمطور)" icon="eye-outline" secondary onPress={onDemo}/><T color={C.muted} size={11} style={{textAlign:'center'}}>لا تظهر البيانات التجريبية في إصدار الإنتاج.</T></View>:null}</ScrollView></KeyboardAvoidingView>;
}
