import React from 'react';
import {Alert,DeviceEventEmitter,View} from 'react-native';
import {C} from '../theme';
import type {Session} from '../types';
import {Action,Card,Header,ItemRow,Pill,Section,T} from '../components/UI';
import {enableDeviceNotifications} from '../lib/notifications';
export function Settings({session,demo,onLogout,capabilities,errors}:{session:Session|null,demo:boolean,onLogout:()=>void,capabilities:Record<string,boolean>,errors:Record<string,string>}){
 return <View><Header title="الإعدادات" subtitle="الاتصال والأمان وصلاحيات WHMCS"/><Card style={{gap:13}}><Pill label={demo?'وضع تجريبي':'API مباشر'} color={demo?C.orange:C.green}/><ItemRow icon="server-security" heading="السيرفر" subtitle={session?.baseUrl||'غير متصل'}/><ItemRow icon="account-key-outline" heading="طريقة الاتصال" subtitle={session?.mode==='admin'?'Admin + API Access Key':session?.mode==='api'?'Restricted API Credentials':'تجريبي'}/><ItemRow icon="fingerprint" heading="التخزين" subtitle="Expo SecureStore (Android Keystore / iOS Keychain)"/></Card><Card style={{marginTop:14,gap:10}}><T weight="800">تحديثات التطبيق</T><T color={C.muted} size={12}>الفحص اليدوي لأحدث إصدار WHMCS</T><Action label="فحص التحديثات" icon="cellphone-arrow-down" onPress={()=>DeviceEventEmitter.emit('whmcs-check-update')}/></Card><Card style={{marginTop:14,gap:10}}>
 <T weight="800">إشعارات WHMCS وواتساب</T>
 <T size={12} color={C.muted}>قنوات مستقلة لواتساب، التذاكر، الفواتير، الطلبات، الخدمات والدومينات. التنبيهات تعرض الحدث فقط بدون بيانات حساسة على شاشة القفل.</T>
 <Action label="تفعيل إشعارات الجهاز" icon="bell-ring-outline" onPress={()=>void enableDeviceNotifications().then(ok=>Alert.alert(ok?'تم التفعيل':'الإشعارات غير مفعلة',ok?'تم السماح بإشعارات WHMCS على الجهاز.':'اسمح بالإشعارات من إعدادات أندرويد.')).catch(()=>Alert.alert('تعذر تفعيل الإشعارات','راجع صلاحيات الإشعارات في أندرويد.'))}/>
 <T size={11} color={C.orange}>التنبيهات المحلية تعمل عند رصد تغييرات أثناء تشغيل التطبيق. وصول إشعارات فورية والتطبيق مغلق يتطلب مصدر Push موثّق على السيرفر؛ لن نستخدم Verify Token كصلاحية Push.</T>
 </Card><Section title="حالة الأقسام"/><Card>{Object.entries(capabilities).filter(([k])=>k.endsWith('.read')).map(([k,v])=><ItemRow key={k} icon={v?'check-circle-outline':'lock-outline'} heading={k} right={<Pill label={v?'يمكن القراءة':'غير متاح'} color={v?C.green:C.orange}/>}/>)}</Card>{Object.keys(errors).length?<><Section title="الأقسام غير المتاحة"/><Card>{Object.entries(errors).map(([k,v])=><T key={k} color={C.orange} size={12}>{k}: {v}</T>)}</Card></>:null}<Card style={{marginTop:18}}><T size={12} color={C.muted}>الاتصال من التطبيق مباشرة إلى includes/api.php؛ لا موديول إضافي. البيانات السرية تظل على الجهاز، ولذلك يُفضّل API Role محدود، منع تسجيل الشاشة، ومسح الجلسة من هاتف غير موثوق. GitHub ليس ضمن بيانات الدخول.</T></Card><View style={{marginTop:20,marginBottom:24}}><Action secondary label={demo?'الخروج من الديمو':'مسح بيانات الاتصال'} icon="logout" onPress={()=>Alert.alert('تأكيد','هل تريد حذف بيانات الربط المحلية؟',[{text:'إلغاء',style:'cancel'},{text:'حذف',onPress:onLogout,style:'destructive'}])}/></View></View>;
}
