import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Alert,BackHandler,Pressable,TextInput,View} from 'react-native';
import {C} from '../theme';
import type {Ticket} from '../types';
import {Action,Avatar,Card,Divider,Empty,Header,Icon,ItemRow,Pill,Search,T} from '../components/UI';
interface ThreadReply {id:string,message:string,name:string,date:string,admin:boolean}
const color=(p:string)=>p==='High'?C.red:p==='Medium'?C.orange:C.green;
export function Tickets({tickets,onReply,onOpen,demo,canReply,total,onLoadMore,moreBusy,error}:{tickets:Ticket[],onReply:(id:number,text:string)=>Promise<boolean>,onOpen:(id:number)=>Promise<ThreadReply[]|null>,demo:boolean,canReply:boolean,total?:number|null,onLoadMore:()=>void,moreBusy:boolean,error?:string}){
 const [q,setQ]=useState(''),[selected,setSelected]=useState<Ticket|null>(null),[reply,setReply]=useState(''),[sending,setSending]=useState(false);
 const [thread,setThread]=useState<ThreadReply[]|null>(null),[fetching,setFetching]=useState(false);
 useEffect(()=>{if(!selected)return;const sub=BackHandler.addEventListener('hardwareBackPress',()=>{setSelected(null);setReply('');return true;});return()=>sub.remove();},[selected]);
 const list=tickets.filter(t=>`${t.id} ${t.number} ${t.subject} ${t.customer} ${t.status}`.toLowerCase().includes(q.toLowerCase()));
 const open=async(ticket:Ticket)=>{setSelected(ticket);setThread(null);setFetching(true);try{setThread(await onOpen(ticket.id));}finally{setFetching(false);}};
 const send=async()=>{if(!selected||!reply.trim()||sending)return; Alert.alert('تأكيد إرسال الرد',demo?'سيتم إضافته محليًا في الديمو فقط':'سيتم إرسال الرد الحقيقي للعميل عبر WHMCS',[
 {text:'إلغاء',style:'cancel'},{text:'إرسال',onPress:async()=>{setSending(true);const ok=await onReply(selected.id,reply.trim());setSending(false);if(ok){setReply('');setSelected(null);}}}
 ]);};
 if(selected) return <View><Pressable onPress={()=>{setSelected(null);setReply('');}} style={{flexDirection:'row-reverse',alignItems:'center',gap:8,marginBottom:19}}><Icon name="arrow-right" color={C.red}/><T color={C.red} weight="700">رجوع للتذاكر</T></Pressable>
 <Header title={`تذكرة #${selected.number}`} subtitle={selected.department}/><Card><View style={{flexDirection:'row-reverse',gap:10,alignItems:'center'}}><Avatar label="TK" color={C.red}/><View style={{flex:1}}><T size={17} weight="800">{selected.subject}</T><T color={C.muted} size={12}>{selected.customer}</T></View></View><Divider/><View style={{flexDirection:'row-reverse',gap:8}}><Pill label={selected.status} color={C.blue}/><Pill label={selected.priority} color={color(selected.priority)}/></View><T style={{marginTop:18,marginBottom:8}} weight="700">المحادثة</T>
 {fetching?<ActivityIndicator color={C.red}/>:thread?thread.length?thread.map((m,i)=><View key={`${m.id}-${i}`} style={{backgroundColor:m.admin?C.redDark:C.surface2,padding:12,borderRadius:13,marginTop:9,gap:5}}><View style={{flexDirection:'row-reverse',justifyContent:'space-between'}}><T weight="800" size={12} color={m.admin?C.red:C.blue}>{m.name}</T><T size={10} color={C.muted}>{m.date}</T></View><T>{m.message.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ')}</T></View>):<T color={C.muted}>لا يوجد ردود حالياً</T>:<T color={C.orange}>لم نتمكن من قراءة الردود الكاملة لهذه التذكرة.</T>}</Card>
 <Card style={{marginTop:14,gap:12}}><T weight="800">إرسال رد للعميل</T><TextInput multiline numberOfLines={5} placeholder="اكتب الرد هنا..." placeholderTextColor={C.muted} value={reply} onChangeText={setReply} textAlignVertical="top" style={{color:C.text,backgroundColor:C.surface2,borderRadius:13,padding:14,minHeight:124,textAlign:'right'}}/><Action label={sending?'جارٍ الإرسال...':'تأكيد وإرسال الرد'} icon="send" onPress={send} disabled={!canReply||sending||!reply.trim()}/>{!canReply?<T color={C.orange} size={11}>صلاحية إرسال الرد تُتحقق من WHMCS عند التنفيذ.</T>:null}</Card></View>;
 return <View><Header title="مركز التذاكر" subtitle="متابعة وفرز والرد على العملاء"/><Search value={q} onChange={setQ} placeholder="رقم التذكرة، العميل، الموضوع..."/><View style={{flexDirection:'row-reverse',gap:7,marginBottom:14}}><Pill color={C.red} label={`${tickets.filter(x=>x.status==='Awaiting Reply').length} تنتظر رد`}/><Pill color={C.blue} label={total!=null?`${tickets.length} من ${total}`:`${tickets.length} محمّلة`}/></View>
 {error?<T color={C.orange} style={{marginBottom:10}}>تعذر قراءة التذاكر: {error}</T>:null}<Card style={{paddingVertical:5}}>{list.length?list.map(t=><ItemRow key={t.id} icon="ticket-outline" heading={t.subject} subtitle={`#${t.number} • ${t.customer} • ${t.updated}`} color={color(t.priority)} onPress={()=>void open(t)} right={<Pill label={t.status==='Awaiting Reply'?'منتظرة':t.status} color={t.status==='Awaiting Reply'?C.red:C.blue}/>}/>):<Empty text="لا توجد تذاكر"/>}</Card>{total!=null&&tickets.length<total&&!error?<View style={{marginTop:14}}><Action label={moreBusy?'جارٍ التحميل...':'تحميل المزيد من WHMCS'} disabled={moreBusy} secondary onPress={onLoadMore}/></View>:null}</View>;
}
