import React,{useState} from 'react';
import {Alert,Pressable,TextInput,View} from 'react-native';
import {C} from '../theme';
import type {Chat} from '../types';
import {Action,Avatar,Card,Empty,Header,Icon,ItemRow,Pill,Search,T} from '../components/UI';
export function WhatsApp({chats,enabled,canSend,onSend,demo}:{chats:Chat[],enabled:boolean,canSend:boolean,onSend:(chatId:string,text:string)=>Promise<boolean>,demo:boolean}){
 const [q,setQ]=useState(''),[selected,setSelected]=useState<Chat|null>(null),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false);
 const send=async()=>{if(!selected||!draft.trim()||busy)return;setBusy(true);const ok=await onSend(selected.id,draft.trim());setBusy(false);if(ok){setDraft('');setSelected(null);}};
 if(selected)return <View><Pressable onPress={()=>setSelected(null)} style={{flexDirection:'row-reverse',alignItems:'center',gap:8,marginBottom:14}}><Icon name="arrow-right" color={C.green}/><T color={C.green}>المحادثات</T></Pressable><Header title={selected.name} subtitle={selected.phone}/><Card style={{minHeight:250,gap:12}}>{selected.messages.map(m=><View key={m.id} style={{alignSelf:m.from==='agent'?'flex-start':'flex-end',backgroundColor:m.from==='agent'?'#183A33':C.surface2,padding:12,borderRadius:15,maxWidth:'90%',gap:4}}><T>{m.body}</T><T color={C.muted} size={10}>{m.at}</T></View>)}</Card><View style={{flexDirection:'row-reverse',gap:10,marginTop:14,alignItems:'center'}}><TextInput value={draft} onChangeText={setDraft} multiline placeholder="رسالتك..." placeholderTextColor={C.muted} style={{flex:1,borderColor:C.stroke,borderWidth:1,borderRadius:14,color:C.text,backgroundColor:C.surface,padding:14,textAlign:'right'}}/><Pressable disabled={!canSend||!draft.trim()||busy} onPress={send} style={{padding:13,borderRadius:14,backgroundColor:canSend?C.green:C.surface2}}><Icon name="send" color={canSend?C.bg:C.muted}/></Pressable></View>{!canSend?<T color={C.orange} size={11} style={{marginTop:12}}>الإرسال الحقيقي يحتاج WhatsApp Adapter معتمد على السيرفر.</T>:null}</View>;
 return <View><Header title="WhatsApp Inbox" subtitle="رسائل العملاء والقوالب والوسائط" right={<Icon name="whatsapp" color={C.green} size={32}/>}/><Card style={{backgroundColor:'#122B29',borderColor:'#245448',marginBottom:16}}><View style={{flexDirection:'row-reverse',alignItems:'center',gap:9}}><Icon name="shield-check" color={C.green}/><T weight="800">{demo?'وضع عرض تجريبي':enabled?'الموديول متصل':'بانتظار توصيل الـAdapter'}</T></View><T size={12} color={C.muted} style={{marginTop:9}}>واجهة Native بالكامل، بدون موديول إضافي. الربط الحقيقي يحتاج API موثّق لموديول WhatsApp الموجود.</T></Card><Search value={q} onChange={setQ} placeholder="اسم العميل أو رقم الهاتف..."/><Card style={{paddingVertical:3}}>{chats.filter(c=>`${c.name} ${c.phone}`.includes(q)).length?chats.filter(c=>`${c.name} ${c.phone}`.includes(q)).map(chat=><ItemRow key={chat.id} icon="message-text" heading={chat.name} subtitle={chat.last} color={C.green} right={chat.unread?<Pill color={C.red} label={`${chat.unread} جديد`}/>:<T size={11} color={C.muted}>{chat.time}</T>} onPress={()=>setSelected(chat)}/>):<Empty icon="whatsapp" text={demo?'لا توجد محادثات':'تظهر المحادثات بعد ربط WhatsApp Adapter'}/>}</Card></View>;
}
